package de.hahn.blog.uldl.model.dataaccess;


import de.hahn.blog.uldl.model.dataaccess.common.ImageAccessView;

import oracle.jbo.Row;
import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 30 21:18:19 CET 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ImageAccessViewImpl
    extends ViewObjectImpl
    implements ImageAccessView
{
    /**
     * This is the default constructor (do not remove).
     */
    public ImageAccessViewImpl()
    {
    }

    /**
     * Returns the bind variable value for bindImageId.
     * @return bind variable value for bindImageId
     */
    public Number getbindImageId()
    {
        return (Number) getNamedWhereClauseParam("bindImageId");
    }

    /**
     * Sets <code>value</code> for bind variable bindImageId.
     * @param value value to bind as bindImageId
     */
    public void setbindImageId(Number value)
    {
        setNamedWhereClauseParam("bindImageId", value);
    }
    
    public Row getImageById(Number aId)
    {
        setbindImageId(aId);
        executeQuery();
        Row row = first();
        return row;
    }
}
