package de.hahn.blog.uldl.model.dataaccess.client;

import oracle.jbo.client.remote.RowImpl;
import oracle.jbo.domain.BlobDomain;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 30 21:18:19 CET 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ImageAccessViewRowClient
    extends RowImpl
{
    /**
     * This is the default constructor (do not remove).
     */
    public ImageAccessViewRowClient()
    {
    }


    public String getContentType()
    {
        return (String) getAttribute("ContentType");
    }

    public BlobDomain getImageData()
    {
        return (BlobDomain) getAttribute("ImageData");
    }

    public Long getImageId()
    {
        return (Long) getAttribute("ImageId");
    }

    public void setContentType(String value)
    {
        setAttribute("ContentType", value);
    }

    public void setImageData(BlobDomain value)
    {
        setAttribute("ImageData", value);
    }

    public void setImageId(Long value)
    {
        setAttribute("ImageId", value);
    }
}
