package de.hahn.blog.uldl.model.dataaccess.client;

import de.hahn.blog.uldl.model.dataaccess.common.ImageAccessView;

import oracle.jbo.Row;
import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 30 21:19:32 CET 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ImageAccessViewClient
    extends ViewUsageImpl
    implements ImageAccessView
{
    /**
     * This is the default constructor (do not remove).
     */
    public ImageAccessViewClient()
    {
    }


    public Row getImageById(oracle.jbo.domain.Number aId)
    {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"getImageById",new String [] {"oracle.jbo.domain.Number"},new Object[] {aId});
        return (Row) _ret;
    }

    public oracle.jbo.domain.Number getbindImageId()
    {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"getbindImageId",null,null);
        return (oracle.jbo.domain.Number)_ret;
    }

    public void setbindImageId(oracle.jbo.domain.Number value)
    {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"setbindImageId",new String [] {"oracle.jbo.domain.Number"},new Object[] {value});
        return;
    }
}
