package de.hahn.blog.uldl.model.dataaccess.common;

import oracle.jbo.Row;
import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 30 21:19:31 CET 2011
// ---------------------------------------------------------------------
public interface ImageAccessView
    extends ViewObject
{
    oracle.jbo.domain.Number getbindImageId();

    void setbindImageId(oracle.jbo.domain.Number value);

    Row getImageById(oracle.jbo.domain.Number aId);
}
