package de.hahn.blog.uldl.model.dataaccess.common;

import oracle.jbo.Row;
import oracle.jbo.domain.BlobDomain;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 30 21:18:19 CET 2011
// ---------------------------------------------------------------------
public interface ImageAccessViewRow
    extends Row
{
    String getContentType();

    BlobDomain getImageData();

    Long getImageId();

    void setContentType(String param);

    void setImageData(BlobDomain param);

    void setImageId(Long param);
}
